"""Initial migration with all existing models

Revision ID: 3f42632fa23f
Revises: 
Create Date: 2026-04-06 19:32:15.455562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f42632fa23f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traditional_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('typical_timing', sa.String(length=200), nullable=True),
    sa.Column('what_you_need', sa.Text(), nullable=True),
    sa.Column('how_to_do_it', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_names', sa.String(length=200), nullable=False),
    sa.Column('wedding_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_step', sa.String(length=50), nullable=True),
    sa.Column('onboarding_preferences', sa.Text(), nullable=True),
    sa.Column('modules_completed', sa.Text(), nullable=True),
    sa.Column('rsvp_enabled', sa.Boolean(), nullable=True),
    sa.Column('rsvp_token', sa.String(length=64), nullable=True),
    sa.Column('rsvp_deadline', sa.Date(), nullable=True),
    sa.Column('rsvp_message', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rsvp_token'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('accommodation_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('block_code', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('rooms_reserved', sa.Integer(), nullable=True),
    sa.Column('welcome_bag', sa.Boolean(), nullable=True),
    sa.Column('welcome_bag_items', sa.Text(), nullable=True),
    sa.Column('welcome_bags_delivered', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ceremony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_contact', sa.String(length=120), nullable=True),
    sa.Column('venue_phone', sa.String(length=50), nullable=True),
    sa.Column('venue_rules', sa.Text(), nullable=True),
    sa.Column('venue_load_in_time', sa.Time(), nullable=True),
    sa.Column('ceremony_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('officiant_name', sa.String(length=200), nullable=True),
    sa.Column('officiant_contact', sa.String(length=120), nullable=True),
    sa.Column('officiant_phone', sa.String(length=50), nullable=True),
    sa.Column('officiant_type', sa.String(length=100), nullable=True),
    sa.Column('ceremony_style', sa.String(length=100), nullable=True),
    sa.Column('traditions', sa.Text(), nullable=True),
    sa.Column('processional_song', sa.String(length=200), nullable=True),
    sa.Column('recessional_song', sa.String(length=200), nullable=True),
    sa.Column('unity_ceremony_song', sa.String(length=200), nullable=True),
    sa.Column('has_unity_ceremony', sa.Boolean(), nullable=True),
    sa.Column('unity_ceremony_type', sa.String(length=100), nullable=True),
    sa.Column('has_special_readings', sa.Boolean(), nullable=True),
    sa.Column('vow_type', sa.String(length=50), nullable=True),
    sa.Column('vow_draft_person1', sa.Text(), nullable=True),
    sa.Column('vow_draft_person2', sa.Text(), nullable=True),
    sa.Column('ceremony_script', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contingency_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_of_timeline_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('who', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_kit_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('packed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floral_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=True),
    sa.Column('flowers', sa.Text(), nullable=True),
    sa.Column('colors', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('thank_you_sent', sa.Boolean(), nullable=True),
    sa.Column('thank_you_sent_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('seat_together', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hair_makeup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('stylist_name', sa.String(length=200), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('trial_date', sa.Date(), nullable=True),
    sa.Column('trial_completed', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honeymoon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('flight_confirmation', sa.String(length=200), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setup_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('designer', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('send_by_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marriage_license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('filing_deadline', sa.Date(), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('documents_needed', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('waiting_period_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('preferred_pronouns', sa.String(length=50), nullable=True),
    sa.Column('name_pronunciation', sa.String(length=200), nullable=True),
    sa.Column('side_label', sa.String(length=100), nullable=True),
    sa.Column('getting_ready_location', sa.String(length=200), nullable=True),
    sa.Column('getting_ready_address', sa.Text(), nullable=True),
    sa.Column('getting_ready_time', sa.Time(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_shot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('people', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('captured', sa.Boolean(), nullable=True),
    sa.Column('timeline_slot', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_contact', sa.String(length=120), nullable=True),
    sa.Column('venue_phone', sa.String(length=50), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.Column('venue_rules', sa.Text(), nullable=True),
    sa.Column('venue_load_in_time', sa.Time(), nullable=True),
    sa.Column('reception_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('catering_style', sa.String(length=100), nullable=True),
    sa.Column('bar_service', sa.String(length=100), nullable=True),
    sa.Column('cake_flavor', sa.String(length=100), nullable=True),
    sa.Column('cake_design', sa.Text(), nullable=True),
    sa.Column('music_type', sa.String(length=100), nullable=True),
    sa.Column('first_dance_song', sa.String(length=200), nullable=True),
    sa.Column('parent_dance_songs', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('centerpiece_description', sa.Text(), nullable=True),
    sa.Column('lighting_notes', sa.Text(), nullable=True),
    sa.Column('cocktail_hour_notes', sa.Text(), nullable=True),
    sa.Column('cocktail_menu', sa.Text(), nullable=True),
    sa.Column('cocktail_entertainment', sa.Text(), nullable=True),
    sa.Column('dance_floor_size', sa.String(length=50), nullable=True),
    sa.Column('kids_activities', sa.Text(), nullable=True),
    sa.Column('kids_sitter_name', sa.String(length=200), nullable=True),
    sa.Column('kids_sitter_phone', sa.String(length=50), nullable=True),
    sa.Column('expected_guest_count', sa.Integer(), nullable=True),
    sa.Column('after_party_venue', sa.String(length=200), nullable=True),
    sa.Column('after_party_address', sa.Text(), nullable=True),
    sa.Column('after_party_start_time', sa.Time(), nullable=True),
    sa.Column('after_party_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('store', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity_requested', sa.Integer(), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('purchased_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehearsal_dinner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_contact', sa.String(length=120), nullable=True),
    sa.Column('venue_phone', sa.String(length=50), nullable=True),
    sa.Column('expected_guest_count', sa.Integer(), nullable=True),
    sa.Column('menu_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('moment', sa.String(length=100), nullable=True),
    sa.Column('spotify_url', sa.String(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speech_toast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('speaker_name', sa.String(length=200), nullable=False),
    sa.Column('speech_type', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('depends_on_id', sa.Integer(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('months_before', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tip_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('suggested_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('envelope_prepared', sa.Boolean(), nullable=True),
    sa.Column('given', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contract_signed', sa.Boolean(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('contract_notes', sa.Text(), nullable=True),
    sa.Column('backup_contact', sa.String(length=200), nullable=True),
    sa.Column('backup_phone', sa.String(length=50), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('deposit_paid', sa.Boolean(), nullable=True),
    sa.Column('balance_due', sa.Float(), nullable=True),
    sa.Column('final_payment_date', sa.Date(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('service_time', sa.Time(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('service_location', sa.String(length=200), nullable=True),
    sa.Column('setup_instructions', sa.Text(), nullable=True),
    sa.Column('meals_needed', sa.Integer(), nullable=True),
    sa.Column('overtime_rate', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('quote_amount', sa.Float(), nullable=True),
    sa.Column('package_details', sa.Text(), nullable=True),
    sa.Column('pros', sa.Text(), nullable=True),
    sa.Column('cons', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding_branding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('additional_colors', sa.Text(), nullable=True),
    sa.Column('primary_font', sa.String(length=100), nullable=True),
    sa.Column('secondary_font', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('monogram_text', sa.String(length=50), nullable=True),
    sa.Column('overall_style', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding_favor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost_per_item', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('assembled', sa.Boolean(), nullable=True),
    sa.Column('assembly_notes', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_type', sa.String(length=100), nullable=True),
    sa.Column('person_name', sa.String(length=200), nullable=True),
    sa.Column('garment_type', sa.String(length=100), nullable=True),
    sa.Column('designer', sa.String(length=200), nullable=True),
    sa.Column('style_number', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('store', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('first_fitting_date', sa.Date(), nullable=True),
    sa.Column('final_fitting_date', sa.Date(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('accessories', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridal_party_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_pronunciation', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('dress_size', sa.String(length=20), nullable=True),
    sa.Column('suit_size', sa.String(length=20), nullable=True),
    sa.Column('shoe_size', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('gift_idea', sa.Text(), nullable=True),
    sa.Column('gift_cost', sa.Float(), nullable=True),
    sa.Column('gift_purchased', sa.Boolean(), nullable=True),
    sa.Column('gift_given', sa.Boolean(), nullable=True),
    sa.Column('has_plus_one', sa.Boolean(), nullable=True),
    sa.Column('plus_one_name', sa.String(length=200), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('processional_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_category_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('covered_by', sa.String(length=200), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_notes', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ceremony_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ceremony_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('reader_name', sa.String(length=200), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ceremony_id'], ['ceremony.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ceremony_timeline_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ceremony_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('music', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ceremony_id'], ['ceremony.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honeymoon_itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('honeymoon_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('accommodation_name', sa.String(length=200), nullable=True),
    sa.Column('accommodation_confirmation', sa.String(length=200), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['honeymoon_id'], ['honeymoon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('source_detail', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('return_by', sa.Date(), nullable=True),
    sa.Column('return_to', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setup_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['inventory_bin.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reception_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dietary_tags', sa.String(length=200), nullable=True),
    sa.Column('guest_count_selected', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reception_id'], ['reception.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packing_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('honeymoon_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('packed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['honeymoon_id'], ['honeymoon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reception_timeline_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reception_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('announcement_script', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reception_id'], ['reception.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seating_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reception_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('table_shape', sa.String(length=50), nullable=True),
    sa.Column('table_size', sa.String(length=50), nullable=True),
    sa.Column('table_role', sa.String(length=50), nullable=True),
    sa.Column('x_position', sa.Float(), nullable=True),
    sa.Column('y_position', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reception_id'], ['reception.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('invitation_sent', sa.Boolean(), nullable=True),
    sa.Column('invitation_sent_date', sa.Date(), nullable=True),
    sa.Column('rsvp_status', sa.String(length=20), nullable=True),
    sa.Column('rsvp_date', sa.Date(), nullable=True),
    sa.Column('attending_ceremony', sa.Boolean(), nullable=True),
    sa.Column('attending_reception', sa.Boolean(), nullable=True),
    sa.Column('meal_choice', sa.String(length=200), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('guest_type', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=100), nullable=True),
    sa.Column('household_group', sa.String(length=200), nullable=True),
    sa.Column('social_groups', sa.Text(), nullable=True),
    sa.Column('rsvp_token', sa.String(length=64), nullable=True),
    sa.Column('rsvp_notes', sa.Text(), nullable=True),
    sa.Column('guest_token', sa.String(length=64), nullable=True),
    sa.Column('is_plus_one', sa.Boolean(), nullable=True),
    sa.Column('plus_one_of', sa.String(length=200), nullable=True),
    sa.Column('gift_received', sa.Boolean(), nullable=True),
    sa.Column('gift_description', sa.Text(), nullable=True),
    sa.Column('thank_you_sent', sa.Boolean(), nullable=True),
    sa.Column('thank_you_sent_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['seating_table.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_token'),
    sa.UniqueConstraint('rsvp_token')
    )
    op.create_table('wedding_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_pronunciation', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('role_category', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('bridal_party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bridal_party_id'], ['bridal_party_member.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seating_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('other_guest_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['other_guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['wedding_id'], ['wedding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_assignments',
    sa.Column('timeline_item_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['wedding_participant.id'], ),
    sa.ForeignKeyConstraint(['timeline_item_id'], ['day_of_timeline_item.id'], ),
    sa.PrimaryKeyConstraint('timeline_item_id', 'participant_id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_assignments')
    op.drop_table('seating_preference')
    op.drop_table('wedding_participant')
    op.drop_table('guest')
    op.drop_table('vendor_note')
    op.drop_table('seating_table')
    op.drop_table('reception_timeline_item')
    op.drop_table('packing_item')
    op.drop_table('menu_item')
    op.drop_table('inventory_item')
    op.drop_table('honeymoon_itinerary')
    op.drop_table('ceremony_timeline_item')
    op.drop_table('ceremony_reading')
    op.drop_table('budget_expense')
    op.drop_table('budget_category_limit')
    op.drop_table('bridal_party_member')
    op.drop_table('attire')
    op.drop_table('wedding_favor')
    op.drop_table('wedding_branding')
    op.drop_table('wedding_access')
    op.drop_table('vendor_quote')
    op.drop_table('vendor')
    op.drop_table('tip_item')
    op.drop_table('task')
    op.drop_table('speech_toast')
    op.drop_table('song')
    op.drop_table('rehearsal_dinner')
    op.drop_table('registry_item')
    op.drop_table('reception')
    op.drop_table('photo_shot')
    op.drop_table('person')
    op.drop_table('marriage_license')
    op.drop_table('invitation')
    op.drop_table('inventory_bin')
    op.drop_table('honeymoon')
    op.drop_table('hair_makeup')
    op.drop_table('guest_group')
    op.drop_table('gift')
    op.drop_table('floral_item')
    op.drop_table('emergency_kit_item')
    op.drop_table('day_of_timeline_item')
    op.drop_table('contingency_plan')
    op.drop_table('comment')
    op.drop_table('ceremony')
    op.drop_table('budget')
    op.drop_table('activity_log')
    op.drop_table('accommodation')
    op.drop_table('wedding')
    op.drop_table('user')
    op.drop_table('traditional_element')
    # ### end Alembic commands ###
